### ISSUE TITLE
Failed to fetch baseUrl

### ISSUE THREAD

**Issue by adityaas26** [gridsome/gridsome-starter-wordpress#13]
I am unable to fetch data from the WordPress url. I simply put the url of the WordPress website in the **baseUrl** field.
The error says: 
>Error: Failed to fetch baseUrl https://discover.wordpress.com/
    at WordPressSource.fetchWordPressContent (Z:\My Work\Projects\sample-project\node_modules\@gridsome\source-wordpress\index.js:33:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

Here's the code in gridsome.confg.js: 
```javascript
module.exports = {
  siteName: 'Gridsome',
  siteDescription: 'A WordPress starter for Gridsome',
  plugins: [
    {
      use: '@gridsome/source-wordpress',
      options: {
        baseUrl: 'https://discover.wordpress.com/', // required
        typeName: 'WordPress', // GraphQL schema name (Optional)
        perPage: 3, // How many posts to load from server per request (Optional)
        concurrent: 10, // How many requests to run simultaneously (Optional)
        routes: {
          post: '/:year/:month/:day/:slug', //adds route for "post" post type (Optional)
          post_tag: '/tag/:slug' // adds route for "post_tag" post type (Optional)
        }
      }
    }
  ]
}
```

Everything else is the same as in the **gridsome WordPress starter template**.

**Comment by adityaas26** [comment]
> Remove the selected code in 'WordPressPost.vue' file.
> <img alt="Screenshot 2019-05-08 at 15 13 20" width="259" src="https://user-images.githubusercontent.com/12196520/57377893-d9d91000-71a3-11e9-86b6-3af438798051.png">

That didn't work for me!

**Comment by martifenosa** [comment]
@adityaas26 Could you solve it? Where do you use this var 'status'?
If I recall correctly the error was coming from the 'templates' folder files, if you remove those the rest should work.

**Comment by thetre97** [comment]
@adityaas26 I tried https://discover.wordpress.com, and it doesn't look like they have the REST API enabled? Try using https://wordpress.org as your baseUrl instead.

**Comment by adityaas26** [comment]
> @adityaas26 I tried https://discover.wordpress.com, and it doesn't look like they have the REST API enabled? Try using https://wordpress.org as your baseUrl instead.

Yes, @thetre97 the problem's with the **wordpress.com** domain which does not have the required REST API support. You can get the support by adding your own custom domain to your WordPress sites.

**Comment by lorvent** [comment]
I have tried with my own wordpress site but still it doesn't work.

i am getting same error, i tried removing code from `WordpressPost.vue` but still it doesn't work.

**Comment by lorvent** [comment]
after testing with many wordpress sites, i can confirm onething.

if a wp site was started long back say 5yrs back..then it throws

```js
TypeError: Cannot destructure property `status` of 'undefined' or 'null'.
    at WordPressSource.fetch (C:\laragon\www\my-gridsome-wp-site\src\plugins\wp-source\index.js:199:40)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

but if it is a new wp installation, then it works fine.

so there must be something in old wp installations, which is root cause of the problem.

**Comment by vdilly** [comment]
I just had this issue, in my case, there was an echo() function left in one of my functions.php file, that outputed some text in my REST API response, turning it into an unvalid json.
The error was thrown during the getTaxonomies() function.

You can try to access all your REST API url to check if the datas are good, or you can just console.log your data response in each get functions of source-wordpress/index.js file.

For example :
`  async getTaxonomies(actions) {
    const { data } = await this.fetch("wp/v2/taxonomies", {}, {});
    console.log(data);
   ...
`

**Comment by VivianSolide** [comment]
@adityaas26 : I'm not able to access to this url: https://discover.wordpress.com/wp-json/wp/v2/posts
Are your permalinks properly set?

Check your permalinks options on https://discover.wordpress.com/wp-admin/options-permalink.php
The wp-json thing doesn't work with "Plain" option.

:warning: Be aware that changing permalinks right now could lead to a lot of SEO issues.

:heavy_check_mark: The best option could be to try this with a fresh installation and tell me if it's ok or not.

Hope this helps
